### ISSUE TITLE
Simple query not running in v0.4.0: `isSchemaChanged is not defined error`

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#144]
I've downloaded the latest Docker image for 0.4.0 of the Explorer, and I'm trying to run the simplest query after creating a graph in version 0.4.0.

```sh
$ docker compose up
[+] Running 0/0
 ⠋ Container kuzudb-explorer-1  Recrea...                               0.0s 
Attaching to explorer-1
explorer-1  | [15:06:41.207] INFO (1): Access mode: READ_ONLY
explorer-1  | [15:06:41.424] INFO (1): Version of Kùzu: 0.4.0
explorer-1  | [15:06:41.424] INFO (1): Storage version of Kùzu: 27
explorer-1  | [15:06:41.425] INFO (1): Deployed server started on port: 8000
```

![image](https://github.com/kuzudb/explorer/assets/35005448/fb2af438-aaf4-419a-bde8-bcde9ae56c90)

Not sure if the issue originates in the Node.js client or the way the schema is passed to the Explorer, so I've opened this as a bug here.

### Update

Seems like the issue is only occurring in `READ_ONLY` mode (the queries work fine in `READ_WRITE` mode)
Here's my docker compose:

```
services:
  explorer:
    image: kuzudb/explorer:latest
    restart: unless-stopped
    environment:
      - MODE=READ_ONLY
    ports:
      - 8000:8000
    volumes:
      - ./social_network:/database

volumes:
  social_network:
```
